const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description: "Bluetooth technology lets you connect it with compatible devic",
    brand: "Apple",
    category: "Electronics",
    price: 10.99,
    countlnStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "test 2",
    image: "/images/phone.jpg",
    description: "lorem compatible devic",
    brand: "Apple",
    category: "Electronics",
    price: 29.99,
    countlnStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "test 3",
    image: "/images/camera.jpg",
    description: "lorem compatible devic",
    brand: "Apple",
    category: "Electronics",
    price: 29.99,
    countlnStock: 10,
    rating: 2,
    numReviews: 12,
  },
];

export default products;
